### ISSUE TITLE
feat: change filename in releases to allow automatic download of newest release

### ISSUE THREAD

**Issue by kamellemann** [michaelmsonne/ManagedIdentityPermissionManager#11]
# Feature Request

**Describe the Feature Request**

change filename in releases to allow automatic download of newest release with powershell like this way
$repo = "michaelmsonne/ManagedIdentityPermissionManager"
$file = "msitool.exe"

$releases = "https://api.github.com/repos/$repo/releases"

Write-Host Determining latest release
$tag = (Invoke-WebRequest $releases | ConvertFrom-Json)[0].tag_name

$download = "https://github.com/$repo/releases/download/$tag/$file"

**Describe Preferred Solution**

**Describe Alternatives**

**Related Code**

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
Yes / No _(Help can be provided if you need assistance submitting a PR)_

**Comment by michaelmsonne** [comment]
In the tool itself or bu another usecase ? :)

**Comment by michaelmsonne** [comment]
The code for this will come in the new v. @kamellemann :)

**Comment by michaelmsonne** [comment]
Added in https://github.com/michaelmsonne/ManagedIdentityPermissionManager/pull/15 and release is out: https://github.com/michaelmsonne/ManagedIdentityPermissionManager/releases
