### ISSUE TITLE
feat: Manually define which tenant to connect to

### ISSUE THREAD

**Issue by fzmindcore** [michaelmsonne/ManagedIdentityPermissionManager#14]
# Feature Request

**Describe the Feature Request**

I'd like to be able to choose which tenant to connect to (useful in scenario's where I'm working outside of the main tenant, such as a demo environment).

**Describe Preferred Solution**

A field next to the 'Connect Microsoft Graph' button on the right that can be optionally filled in with a tenant ID (or domain name that resolves to a tenant ID).

**If the feature request is approved, would you be willing to submit a PR?**
Yes

**Comment by michaelmsonne** [comment]
Will lokk at it ;)
