### ISSUE TITLE
feat: Authentication using passkey

### ISSUE THREAD

**Issue by JonathanMayer87** [michaelmsonne/ManagedIdentityPermissionManager#8]
# Feature Request

**Describe the Feature Request**

**Describe Preferred Solution**

As best practice from Microsoft is to use phishing resistant login method. Except if I am wrong, this is currently not possible using the current version.

**Describe Alternatives**

**Related Code**

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
Yes / No _(Help can be provided if you need assistance submitting a PR)_

**Comment by michaelmsonne** [comment]
Thanks for the report - will look into it and see if I can do anything 🙂

**Comment by michaelmsonne** [comment]
Hi @JonathanMayer87 ,

Have looked a bit into this, and from a code part there is nothing I can do at the moment - but the way to "enfoce" phishing resistant login can be a https://learn.microsoft.com/en-us/entra/identity/authentication/concept-authentication-strengths and then target users to this for Microsoft Graph.

But yes, not a "solution".. We can hope @Microsoft will add some on a later moment 🤞
